trigger:
  branches:
    include: ['master']
  tags:
    include: ['*']

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build'

- bash: |
    echo ">>> Publish"
    npm run publish -p $(VSCODE_MARKETPLACE_TOKEN)
    displayName: 'Publish'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))