steps:
  - bash: |
      echo ">>> Publish"
      yarn deploy -p $(VSCODE_MARKETPLACE_TOKEN)
    displayName: Publish
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: GitHubRelease@1
    inputs:
        gitHubConnection: github.com_loonskai
        repositoryName: "$(Build.Repository.Name)"
        action: "create"
        target: "$(Build.SourceVersion)"
        tagSource: "gitTag"
        tagPattern: "v*"
        releaseNotesFilePath: "CHANGELOG.md"
        changeLogCompareToRelease: "lastFullRelease"
        changeLogType: "commitBased"