steps:
  - task: GitHubRelease@1
    inputs:
        gitHubConnection: github.com_loonskai
        repositoryName: "$(Build.Repository.Name)"
        action: "create"
        target: "$(Build.SourceVersion)"
        tagSource: "gitTag"
        tagPattern: "v*"
        releaseNotesFilePath: "CHANGELOG.md"
        changeLogCompareToRelease: "lastFullRelease"
        changeLogType: "commitBased"