variables:
  azure_pipelines: true

trigger:
  branches:
    include: ['master']
  tags:
    include:
      - v*

stages:
  - stage: build
    jobs:
      - job: Windows
        pool:
          vmImage: windows-latest
        steps:
          - template: common/build.yml
          - template: common/test.yml
          
      - job: Linux
        pool:
          vmImage: ubuntu-latest
          steps:
            - template: common/build.yml
            - template: common/test.yml

      - job: macOS
        pool:
          vmImage: macos-latest
          steps:
            - template: common/build.yml
            - template: common/test.yml
  
  - stage: release
    jobs:
      - job: Linux
        pool:
        vmImage: ubuntu-latest
        steps:
          - template: common/build.yml
          - template: common/test.yml
          - template: common/release.yml